### PR TITLE
Issue 539

### LINKED ISSUE #539: Add functionality and optimize

### LINKED ISSUE #540: Solution has no back button to allow user to navigate back from previous page.

### LINKED ISSUE #544: Update styling
Image display for homepage on mobile does not look right and needs to be fixed, affected by styling applied through figure.
Set universal style for back button to ensure streamlined design.

### LINKED ISSUE #545: Fix text rendering
Long titles for spotlight text results in visual bug, add text-overflow ellipsis to ensure presentable design.

### LINKED ISSUE #546: Banner image
After updating some image-handling banner image is presented wrong, update and set max-height to avoid visual bug.

### PR DESCRIPTION
**Pull request by skjulestad**
Add back button
Update styling
Fix text rendering for spotlight title
Image rendering

### CODE REVIEW

File: src/main/resources/react4xp/components/PageProcessor.ts [hunk 1]
```diff
@@ -1,17 +1,25 @@
...
         page: {
             type: 'page',
             path: '/',
             config: component.config || {},
             descriptor: 'com.enonic.app.hmdb:main',
-            regions,
-        }
+            regions
+        },
+        ...(parentSegment !== parentBaseSegment ? {parent: parentSegment} : {})
```
Comment (pmi) [inline src/main/resources/react4xp/components/PageProcessor.ts]: It's better if you define the propery and set it's value depending on the condition to value or undefined instead of making whole property conditional, because it's hard to find it now

File: src/main/resources/react4xp/components/PageProcessor.ts [hunk 2]
```diff
@@ -1,17 +1,25 @@
...
-
+import type {ComponentProcessorFunction} from '@enonic-types/lib-react4xp/DataFetcher';
 
 export const pageProcessor: ComponentProcessorFunction<'com.enonic.app.hmdb:main'> = (props) => {
     const component = props.component as PageComponent;
     const regions = component?.regions || {};
+    const site = getSite();
+
+    const baseUrl = pageUrl({path: site._path});
+    const parentSegment = props.request.path.split('/').slice(0, -1).join('/');
```
Comment (pmi) [inline src/main/resources/react4xp/components/PageProcessor.ts]: This line is used a lot in different processors, create a util function that accepts path and returns a parent and use it everywhere.

File: src/main/resources/react4xp/components/content/ArticleProcessor.ts [hunk 3]
```diff
@@ -96,5 +96,6 @@ export const articleProcessor: ComponentProcessorFunction<PageDescriptor> = (par
         tags: data.tags || [],
         blocks: processedBlocks,
         spotlight,
+        parent: params.request.path.split('/').slice(0, -1).join('/'),
```
Comment (pmi) [inline src/main/resources/react4xp/components/content/ArticleProcessor.ts]: util function

File: src/main/resources/react4xp/components/content/PersonProcessor.ts [hunk 4]
```diff
@@ -49,5 +49,6 @@ export const personProcessor: ComponentProcessorFunction<PageDescriptor>
         }),
         birthDate: params.content.data.dateofbirth,
         restPhotos: extraPhotos,
+        parent: params.request.path.split('/').slice(0, -1).join('/'),
```
Comment (pmi) [inline src/main/resources/react4xp/components/content/PersonProcessor.ts]: util function

File: src/main/resources/react4xp/components/content/PlaylistProcessor.ts [hunk 5]
```diff
@@ -88,7 +88,8 @@ export const playlistProcessor: ComponentProcessorFunction<PageDescriptor> = par
             displayName: content.displayName,
             description: playlistData.description || 'No description available.',
             movies: movies, // Movies with image data included
-            url
+            url,
+            parent: params.request.path.split('/').slice(0, -1).join('/'),
```
Comment (pmi) [inline src/main/resources/react4xp/components/content/PlaylistProcessor.ts]: util function

**Review by pmi — CHANGES_REQUESTED** [review]
